"""initial migration

Revision ID: 8f1af2863a5d
Revises: 
Create Date: 2018-02-13 13:59:20.695966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f1af2863a5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Images',
    sa.Column('imageHASH', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('filetype', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.Column('origin', sa.String(length=100), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('imageHASH')
    )
    op.create_table('Tags',
    sa.Column('tagID', sa.Integer(), nullable=False),
    sa.Column('tagName', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('tagID')
    )
    op.create_table('Labels',
    sa.Column('labelID', sa.Integer(), nullable=False),
    sa.Column('imageID', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('label', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['imageID'], ['Images.imageHASH'], ),
    sa.PrimaryKeyConstraint('labelID')
    )
    op.create_table('ProtestNonProtestVotes',
    sa.Column('protestVoteID', sa.Integer(), nullable=False),
    sa.Column('imageID', sa.String(length=100), nullable=True),
    sa.Column('is_protest', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['imageID'], ['Images.imageHASH'], ),
    sa.PrimaryKeyConstraint('protestVoteID')
    )
    op.create_table('TaggedImages',
    sa.Column('imageID', sa.String(length=100), nullable=True),
    sa.Column('tagID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['imageID'], ['Images.imageHASH'], ),
    sa.ForeignKeyConstraint(['tagID'], ['Tags.tagID'], )
    )
    op.create_table('Votes',
    sa.Column('comparisonID', sa.Integer(), nullable=False),
    sa.Column('imageID_1', sa.String(length=100), nullable=True),
    sa.Column('imageID_2', sa.String(length=100), nullable=True),
    sa.Column('vote', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['imageID_1'], ['Images.imageHASH'], ),
    sa.ForeignKeyConstraint(['imageID_2'], ['Images.imageHASH'], ),
    sa.PrimaryKeyConstraint('comparisonID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Votes')
    op.drop_table('TaggedImages')
    op.drop_table('ProtestNonProtestVotes')
    op.drop_table('Labels')
    op.drop_table('Tags')
    op.drop_table('Images')
    # ### end Alembic commands ###
