"""empty message

Revision ID: 8f56d2998ece
Revises: cbc26821f2d6
Create Date: 2018-03-05 17:56:50.633690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f56d2998ece'
down_revision = 'cbc26821f2d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Comparisons',
    sa.Column('comparisonID', sa.Integer(), nullable=False),
    sa.Column('imageID_1', sa.String(length=100), nullable=True),
    sa.Column('imageID_2', sa.String(length=100), nullable=True),
    sa.Column('win1', sa.Integer(), nullable=False),
    sa.Column('win2', sa.Integer(), nullable=False),
    sa.Column('tie', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.CheckConstraint('imageID_1 <> imageID_2', name='check-is-different'),
    sa.CheckConstraint('max(imageID_1, imageID_2) = imageID_2', name='ordered-pair'),
    sa.ForeignKeyConstraint(['imageID_1'], ['Images.imageHASH'], ),
    sa.ForeignKeyConstraint(['imageID_2'], ['Images.imageHASH'], ),
    sa.PrimaryKeyConstraint('comparisonID'),
    sa.UniqueConstraint('imageID_1', 'imageID_2', name='pair')
    )
    op.drop_table('Votes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Votes',
    sa.Column('comparisonID', sa.INTEGER(), nullable=False),
    sa.Column('imageID_1', sa.VARCHAR(length=100), nullable=True),
    sa.Column('imageID_2', sa.VARCHAR(length=100), nullable=True),
    sa.Column('vote', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['imageID_1'], ['Images.imageHASH'], ),
    sa.ForeignKeyConstraint(['imageID_2'], ['Images.imageHASH'], ),
    sa.PrimaryKeyConstraint('comparisonID')
    )
    op.drop_table('Comparisons')
    # ### end Alembic commands ###
