"""empty message

Revision ID: c809295ddcfc
Revises: 8f56d2998ece
Create Date: 2018-03-06 00:27:15.205262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c809295ddcfc'
down_revision = '8f56d2998ece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Labels', sa.Column('source', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Labels', 'source')
    # ### end Alembic commands ###
