"""empty message

Revision ID: cbc26821f2d6
Revises: 8f1af2863a5d
Create Date: 2018-02-21 13:44:32.876381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbc26821f2d6'
down_revision = '8f1af2863a5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ProtestNonProtestVotes', sa.Column('annotator', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ProtestNonProtestVotes', 'annotator')
    # ### end Alembic commands ###
